version: '3'
services:
  db:
    image: mongo:7
    restart: always
    command: mongod --replSet rs0 --bind_ip_all
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  blobstorage:
    image: minio/minio
    restart: always
    command: server /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
      MINIO_BROWSER: off

  app:
    build: .
    depends_on:
      - db
      - blobstorage
    ports:
      - 3000:3000
    environment:
      MONGODB_URL: mongodb://db/
      ADMIN_LOGIN: admin:admin
      MINIO_ENDPOINT: blobstorage
      MINIO_PORT: 9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
      MINIO_USE_SSL: 'false'
      BODY_SIZE_LIMIT: 20971520
